spring:
  datasource:
    driverClassName: org.sqlite.JDBC
    url: jdbc:sqlite:doc/data/diyfile.db?date_string_format=yyyy-MM-dd HH:mm:ss
    hikari:
      # 连接池最大连接数
      maximum-pool-size: 20
      # 空闲时保持最小连接数
      minimum-idle: 5
      # 空闲连接存活时间
      idle-timeout: 300000
      # 连接超时时间
      connection-timeout: 5000
      # 检测连接是否有效
      connection-test-query: select 1
  # 缓存
  cache:
    type: CAFFEINE
    caffeine:
      spec: maximumSize=500,initialCapacity=100,expireAfterAccess=600s

# MyBatis配置
mybatis:
  # 搜索指定包别名
  typeAliasesPackage: com.besscroft.diyfile.common.entity
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/*Mapper.xml
  configuration:
    cache-enabled: false

# mybatis-plus 配置
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: del # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 0 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 1 # 逻辑未删除值(默认为 0)

# Actuator 配置
management:
  endpoints:
    web:
      exposure:
        # 监控项配置
        include: '*'
  endpoint:
    health:
      # 开启显示全部细节
      show-details: always
    shutdown:
      # 启用接口关闭 SpringBoot
      enabled: false
  # Micrometer 配置
  metrics:
    tags:
      application: ${spring.application.name}

# SpringDoc 配置
springdoc:
  api-docs:
    enabled: ${DOC_ENABLE:false}
    path: "/api-docs"
  swagger-ui:
    enabled: ${DOC_ENABLE:false}
    path: "/swagger-ui.html"
  # 配置扫描的包
  packagesToScan: com.besscroft.diyfile.controller
  show-actuator: false
  cache:
    disabled: false
  pre-loading-enabled: true

sa-token:
  # token名称 (同时也是cookie名称)
  token-name: Authorization
  # token前缀
  token-prefix: Bearer
  # token有效期，单位s 默认30天, -1代表永不过期
  timeout: 2592000
  # token临时有效期 (指定时间内无操作就视为token过期) 单位: 秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为true时允许一起登录, 为false时新登录挤掉旧登录)
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个token (为true时所有登录共用一个token, 为false时每次登录新建一个token)
  is-share: true
  # token风格
  token-style: uuid
  # 是否输出操作日志
  is-log: false
  # Cookie配置
  is-read-cookie: false
  # logo打印
  isPrint: false
